// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaF6_5snDgYC1zOzL3Re1lEl0Ruue3reg',
    appId: '1:18490494111:web:72cd4e2d01f917fabbe6aa',
    messagingSenderId: '18490494111',
    projectId: 'bloomix-mobile-app',
    authDomain: 'bloomix-mobile-app.firebaseapp.com',
    storageBucket: 'bloomix-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwcpK5frhZsF6sZ_XGf63TJXbwO_eoh7c',
    appId: '1:18490494111:android:9bb1c40e10c3f962bbe6aa',
    messagingSenderId: '18490494111',
    projectId: 'bloomix-mobile-app',
    storageBucket: 'bloomix-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeMv5AObj-U3ge34ecSsrQazeLp1q3TC0',
    appId: '1:18490494111:ios:16a877d75cca5b96bbe6aa',
    messagingSenderId: '18490494111',
    projectId: 'bloomix-mobile-app',
    storageBucket: 'bloomix-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.bloomixMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeMv5AObj-U3ge34ecSsrQazeLp1q3TC0',
    appId: '1:18490494111:ios:16a877d75cca5b96bbe6aa',
    messagingSenderId: '18490494111',
    projectId: 'bloomix-mobile-app',
    storageBucket: 'bloomix-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.bloomixMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaF6_5snDgYC1zOzL3Re1lEl0Ruue3reg',
    appId: '1:18490494111:web:e6eccde8e1c1a4dcbbe6aa',
    messagingSenderId: '18490494111',
    projectId: 'bloomix-mobile-app',
    authDomain: 'bloomix-mobile-app.firebaseapp.com',
    storageBucket: 'bloomix-mobile-app.firebasestorage.app',
  );

}